version: '3.3'

services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v3.2.1
    container_name: "tyk-gateway"
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - tyk
    volumes:
      - ./tyk/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
    environment:
      - TYK_GW_SECRET=foo
      - TYK_LOGLEVEL=debug
    depends_on:
      - tyk-redis

  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

networks:
  tyk:
